apiVersion: v1
kind: Service
metadata:
  name: pokedex-client
spec:
  type: LoadBalancer
  selector:
    app: pokedex-client
  ports:
    - port: 80           # Puerto expuesto por el LoadBalancer (lo que el usuario ve)
      targetPort: 80     # Puerto donde escucha el contenedor (el puerto interno de tu aplicaci√≥n cliente)